-- ============================================================
-- 교회 슈퍼플래너 (Church Solutions) — Supabase 스키마
-- src/lib/supabase-db.ts, src/types/db.ts 구조에 맞춤
-- Supabase Dashboard → SQL Editor에서 실행
-- ============================================================

-- 1. settings (교회 설정, 단일 행)
CREATE TABLE IF NOT EXISTS public.settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  church_name text NOT NULL DEFAULT '',
  depts text NOT NULL DEFAULT '',
  fiscal_start text NOT NULL DEFAULT '1',
  address text,
  pastor text,
  business_number text
);

-- 2. members (교인)
CREATE TABLE IF NOT EXISTS public.members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT '',
  dept text,
  role text,
  birth text,
  gender text,
  phone text,
  address text,
  family text,
  status text,
  source text,
  prayer text,
  memo text,
  mokjang text,
  photo text,
  created_at timestamptz DEFAULT now()
);

-- 3. attendance (출석: member_id + week_num + year)
CREATE TABLE IF NOT EXISTS public.attendance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id uuid NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  week_num int NOT NULL,
  year int NOT NULL,
  status text NOT NULL DEFAULT 'n' CHECK (status IN ('p', 'a', 'n')),
  reason text
);
CREATE INDEX IF NOT EXISTS idx_attendance_member_year ON public.attendance(member_id, year);

-- 4. notes (교인별 메모/기도/방문/이벤트)
CREATE TABLE IF NOT EXISTS public.notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id uuid NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  date text NOT NULL DEFAULT '',
  type text NOT NULL DEFAULT 'memo' CHECK (type IN ('memo', 'prayer', 'visit', 'event')),
  content text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notes_member ON public.notes(member_id);

-- 5. plans (플래너)
CREATE TABLE IF NOT EXISTS public.plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL DEFAULT '',
  date text NOT NULL DEFAULT '',
  time text,
  cat text,
  memo text
);

-- 6. sermons (주보/설교)
CREATE TABLE IF NOT EXISTS public.sermons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date text NOT NULL DEFAULT '',
  service text NOT NULL DEFAULT '',
  bible_text text,
  title text,
  core text,
  status text NOT NULL DEFAULT '구상중',
  notes text
);

-- 7. visits (심방/상담)
CREATE TABLE IF NOT EXISTS public.visits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date text NOT NULL DEFAULT '',
  member_id uuid REFERENCES public.members(id) ON DELETE SET NULL,
  type text,
  content text NOT NULL DEFAULT ''
);

-- 8. income (헌금/수입)
CREATE TABLE IF NOT EXISTS public.income (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date text NOT NULL DEFAULT '',
  type text NOT NULL DEFAULT '',
  amount numeric NOT NULL DEFAULT 0,
  donor text,
  method text,
  memo text
);

-- 9. expense (지출)
CREATE TABLE IF NOT EXISTS public.expense (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT '',
  item text,
  amount numeric NOT NULL DEFAULT 0,
  resolution text,
  memo text
);

-- 10. budget (예산, 연도별 카테고리)
CREATE TABLE IF NOT EXISTS public.budget (
  category text NOT NULL,
  year int NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  PRIMARY KEY (category, year)
);

-- 11. checklist (주차별 체크리스트)
CREATE TABLE IF NOT EXISTS public.checklist (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_key text NOT NULL,
  text text NOT NULL DEFAULT '',
  done boolean NOT NULL DEFAULT false,
  sort_order int NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_checklist_week ON public.checklist(week_key);

-- ============================================================
-- RLS (Row Level Security) — anon으로 읽기/쓰기 허용 시
-- ============================================================
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sermons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checklist ENABLE ROW LEVEL SECURITY;

-- 모든 테이블: anon 역할에 대해 전체 허용 (단일 교회/단일 프로젝트 가정)
-- 이미 같은 이름 정책이 있으면 아래 줄은 실패하므로, 필요 시 Supabase Dashboard에서 기존 정책 삭제 후 재실행
CREATE POLICY "settings_anon_all" ON public.settings FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "members_anon_all" ON public.members FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "attendance_anon_all" ON public.attendance FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "notes_anon_all" ON public.notes FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "plans_anon_all" ON public.plans FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "sermons_anon_all" ON public.sermons FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "visits_anon_all" ON public.visits FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "income_anon_all" ON public.income FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "expense_anon_all" ON public.expense FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "budget_anon_all" ON public.budget FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "checklist_anon_all" ON public.checklist FOR ALL TO anon USING (true) WITH CHECK (true);
