import type { CSSProperties } from "react";
import { APP_MODAL } from "@/styles/appModalTokens";

/** 활동 기록 추가 모달 — 성도 관리 +버튼 시안 (01~05) */
export const ACTIVITY_RECORD_MODAL = {
  fontKR: APP_MODAL.fontKR,
  width: APP_MODAL.width,
  height: 500,
  zIndex: APP_MODAL.zIndex,
  radius: 12,
  shadow: APP_MODAL.cardShadow,
  headerBg: "#f0f0f2",
  headerHeight: 88,
  /** 우상단 회색 사선 장식 폭 */
  headerWedgeWidth: 168,
  titleSize: APP_MODAL.titleSize,
  titleWeight: APP_MODAL.titleWeight,
  titleColor: APP_MODAL.ink,
  subtitleSize: 14,
  subtitleWeight: 400,
  subtitleColor: "#9ca0a8",
  titleToSubtitle: 4,
  headerPadX: APP_MODAL.padding,
  headerPadTop: 22,
  headerPadBottom: 18,
  bodyPadX: APP_MODAL.padding,
  bodyPadBottom: APP_MODAL.padding,
  fieldRowGap: 10,
  fieldToTextareaGap: 12,
  textareaToButtonsGap: 20,
  fieldHeight: APP_MODAL.inputHeight,
  fieldRadius: APP_MODAL.inputRadius,
  fieldBg: APP_MODAL.inputBg,
  fieldFontSize: APP_MODAL.inputFontSize,
  fieldColor: APP_MODAL.ink,
  fieldPlaceholder: "#a3a8b0",
  dateFlex: 1.58,
  categoryFlex: 1,
  textareaMinHeight: 216,
  textareaPad: 16,
  textareaBorder: "#e5e6ea",
  textareaFontSize: 15,
  textareaLineHeight: 1.55,
  dropdownBg: "#ffffff",
  dropdownBorder: "#ebebed",
  dropdownShadow: "0 8px 24px rgba(0, 0, 0, 0.1)",
  dropdownItemPadY: 12,
  dropdownItemPadX: 16,
  dropdownItemHoverBg: "#f4f4f6",
  btnHeight: APP_MODAL.btnHeight,
  btnRadius: APP_MODAL.btnRadius,
  btnGap: APP_MODAL.btnGap,
  btnFontSize: 15,
  btnFontWeight: 600,
  btnCancelBorder: "#e3e4e8",
  btnCancelBg: "#ffffff",
  btnCancelColor: APP_MODAL.ink,
  btnSubmitBg: APP_MODAL.ink,
  btnSubmitColor: "#ffffff",
  dividerColor: "rgba(0,0,0,0.06)",
} as const;

export function activityRecordCardStyle(): CSSProperties {
  return {
    width: ACTIVITY_RECORD_MODAL.width,
    maxWidth: "100%",
    height: ACTIVITY_RECORD_MODAL.height,
    minHeight: ACTIVITY_RECORD_MODAL.height,
    maxHeight: ACTIVITY_RECORD_MODAL.height,
    borderRadius: ACTIVITY_RECORD_MODAL.radius,
    background: "#ffffff",
    border: APP_MODAL.cardBorder,
    boxShadow: ACTIVITY_RECORD_MODAL.shadow,
    fontFamily: ACTIVITY_RECORD_MODAL.fontKR,
    boxSizing: "border-box",
    overflow: "hidden",
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
  };
}
