/** 성도 관리 — 디자이너 시안 (1440px, grayscale) */
export const MEMBER_MGMT = {
  fontKR: "'Pretendard', system-ui, -apple-system, sans-serif",
  gap: 16,
  /** 검색·등록 바 */
  toolbarGap: 12,
  searchHeight: 44,
  searchRadius: 10,
  searchBorder: "#e2e4e8",
  searchBg: "#ffffff",
  searchPlaceholder: "#a3a8b0",
  searchText: "#1a1c20",
  searchPadX: 16,
  searchFontSize: 14,
  registerHeight: 44,
  registerPadX: 18,
  registerRadius: 10,
  registerBorder: "#e2e4e8",
  registerBg: "#f5f5f6",
  registerBgHover: "#ececee",
  registerText: "#1a1c20",
  registerFontSize: 14,
  registerFontWeight: 600,
  /** 테이블 */
  tableRadius: 12,
  tableBorder: "#e8eaed",
  tableBg: "#ffffff",
  headerBg: "#fafafa",
  headerText: "#6b7280",
  headerFontSize: 13,
  headerFontWeight: 600,
  headerPadY: 14,
  headerPadX: 12,
  rowHeight: 52,
  rowBorder: "#f0f1f3",
  rowHover: "#fafafa",
  rowText: "#374151",
  nameText: "#111827",
  nameFontWeight: 600,
  nameFontSize: 14,
  cellFontSize: 13,
  numText: "#9ca3af",
  avatarSize: 32,
  avatarBg: "#e8eaed",
  avatarText: "#4b5563",
  avatarFontSize: 13,
  avatarFontWeight: 600,
  prayerText: "#374151",
  prayerBadgeBg: "#dbeafe",
  prayerBadgeText: "#2563eb",
  prayerBadgeFontSize: 11,
  prayerBadgeFontWeight: 700,
  prayerBadgePadX: 6,
  prayerBadgeRadius: 6,
  memoMuted: "#9ca3af",
  activityBtnSize: 28,
  activityBtnBorder: "#e2e4e8",
  activityBtnBg: "#ffffff",
  activityBtnHover: "#f5f5f6",
  activityBtnText: "#6b7280",
  dropdownBg: "#ffffff",
  dropdownBorder: "#e2e4e8",
  dropdownShadow: "0 8px 24px rgba(15,23,42,0.1)",
  dropdownRadius: 10,
  dropdownItemPad: "10px 14px",
  dropdownItemHover: "#f5f5f6",
  dropdownSectionLabel: "#9ca3af",
  dropdownSectionFontSize: 11,
} as const;

export const MEMBER_MGMT_COLUMNS = [
  "번호",
  "이름",
  "직분",
  "부서/목장",
  "기도제목",
  "최근심방",
  "메모",
  "활동기록",
] as const;
